import DynamicStyle from '@/components/dynamicStyles'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { store } from '@/redux/store'
import { Provider } from 'react-redux'
import { ReduxProvider } from '@/redux/reduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <DynamicStyle />
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  )
}
